### ISSUE TITLE
Comparison with `test.each`?

### ISSUE THREAD

**Issue by lydell** [SimonAlling/jest-function#1]
How does this compare to Jest's built-in [test.each](https://jestjs.io/docs/en/api#testeachtable-name-fn-timeout)?

**Comment by SimonAlling** [comment]
I didn't know about `test.each` when I created `jest-function`, but, having tried out the former, I'd say this about the latter:

* Less general; more specialized and to the point.
* Philosophically closer to the lambda calculus: A function is something that takes exactly one argument (which can be an _n_-tuple). Think Haskell.
* More strongly typed. Given `function show(x: number) { return x.toString(); }`, you won't be testing that `show(5)` equals `5`, because such a test won't even typecheck. Also no shenanigans with variable-arity functions. Think Haskell.
* Doesn't point out the location of test failures as well (because the call to `expect` isn't in the test file), but displays the input that resulted in an unexpected output by default. (I like to wrap `check(f).against(spec)` in `it` so I can easily see which function failed.)
* The function to be tested decides the types that the specification's input and output values must have, rather than the other way around. This means that type errors are pointed out differently:

  ```typescript
  check(succ).against([
    { in: 4, out: "5" },
  ]);
  ```

  ```
  error TS2322: Type 'string' is not assignable to type 'number'.

  { in: 4, out: "5" },
           ~~~
  ```

  Whereas with `test.each`:

  ```typescript
  test.each([
    [ 4, "5" ],
  ])("succ", (x, y) => expect(succ(x)).toEqual(y));
  ```

  ```
  error TS2345: Argument of type 'string | number' is not assignable to parameter of type 'number'.
    Type 'string' is not assignable to type 'number'.

  ])("succ", (x, y) => expect(succ(x)).toEqual(y));
                                   ~
  ```

As a matter of fact, `jest-function` is the result of writing [tests for `lines-unlines`](https://github.com/SimonAlling/lines-unlines/blob/master/index.test.ts), a TypeScript port of the eponymous Haskell functions.

**Comment by lydell** [comment]
Cool, thanks!
